### PR TITLE
Fixed utils.printoptions

### PR DESCRIPTION
**Pull request by Sciancisco**
FloatFormat was marked as deprecated in numpy 1.14.0 and its deprecation expired in numpy 1.18.0.

Furthermore, FloatingFormat.__call__ takes only 2 positional arguments so it would crash when passing strip_zeros.

After a quick grep in the files, turns out that nor printoptions(True, **kwargs) nor printoptions(strip_zeros=True) was used anywhere, therefore the keyword was removed.

This now works with numpy 1.22.4.

### CODE REVIEW

**Comment by moorepants** [comment]
Thanks for fixing this, but I think there are tests in the test suite that should also be fixed. Are you running the test suite?

**Comment by Sciancisco** [comment]
I must say I didn't... Sorry.

I forgot 1 yaml.load that caused an error in the tests (now fixed).

It fails the three test about the output of `print_properties`and  `print_solid_properties` because the number of "0" is not the same. Which solution do you prefer? Change the tests to fit new output or fix the number of "0" in output or a solution you would propose.

P.S. Running tests was a good idea. Who would've thought?!

**Comment by moorepants** [comment]
I'm fine with updating the tests if it just some minor differences in the display of the outputs.

**Comment by moorepants** [comment]
Some of the test failures were reported here: https://github.com/chrisdembia/yeadon/pull/129

**Comment by Sciancisco** [comment]
On Python 3.9, I have now fixed all tests.

**Comment by moorepants** [comment]
Ok, I'll merge as it. I'm setting up Github actions in #133 so that these tests will run again for future PRs.

**Pull request merged**
