### PR TITLE
Support python3

### PR DESCRIPTION
**Pull request by oliverlee**
This seems to work after running `bin/yeadon` and some other code in [bicycleparameters](https://github.com/moorepants/BicycleParameters)

TODO:

- [ ] Add Travis Python 3 testing
- [ ] Update documentation with notes on Python 3 support
- [ ] Update the setup.py file for Python 3.
- [ ] Create pip and conda packages for Python 3 support (after the release).

### CODE REVIEW

**Comment by moorepants** [comment]
Awesome. Note that we should specify that this only works with Python 3 for the API. I don't think Mayavi supports Python 3 due to the dependency on VTK which has yet to upgrade their Python wrappers.

**Comment by moorepants** [comment]
@oliverlee What's the status on this? Can you finish it up? Looks like one test fails on Python 2.7.

We should also enable Python 3 on Travis.

**Comment by oliverlee** [comment]
I don't have a computer so I can't get to it anytime soon but it worked for
me.

**Comment by moorepants** [comment]
Ok, I added some todo item above.

**Comment by moorepants** [comment]
Closing in favor of #123.

**Pull request closed without merging**
